version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS stor.highloadcup.ru
      - run: ./build.sh
      - run: docker logout stor.highloadcup.ru